name: Regression Tests - Daily Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight

jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Create environment file
        run: |
          mkdir -p environments
          cat > environments/.env.staging << EOF
          BASE_URL=${{ vars.BASE_URL }}
          BASE_API_URL=${{ vars.BASE_API_URL }}
          STORAGE_STATE=.auth/user.json
          TEST_EMAIL=${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD=${{ secrets.TEST_PASSWORD }}
          TEST_CREDIT_CARD=${{ secrets.TEST_CREDIT_CARD }}
          EOF
      - name: Run tests
        run: npx playwright test tests/spec/web/demo.spec.ts --project=chromium
        env:
          TEST_ENV: staging
      - name: Install Allure
        run: npm install -g allure-commandline --save-dev
      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report
      - name: Upload Allure Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: allure-results
          retention-days: 7
          
